# General settings
maxiter: 10000
n_clusters: 3
m: 2
epsilon: 0.00001
seed: 42

# Input/Output
input_image_path: 'data/images/k1_1024x1024.tif'
output_image_path: 'outputs/segmented_image.tif'

# Validity indices to calculate
validity_indices:
  dunn_index: false # Đang bị lỗi tràn bộ nhớ 
  davies_bouldin_index: false
  davies_bouldin_index_sckitlearn: false
  separation_index: false # Đang bị lỗi tràn bộ nhớ 
  partition_coefficient: false
  classification_entropy: true
  fuzzy_hypervolume: true
  cs_index: true

# Debug settings
debug:
  print_time: true
  print_image_size: true
  print_steps: true
  print_U: true
  print_V: true
