# General settings
maxiter: 10000
n_clusters: 2
m: 2
epsilon: 0.00001
seed: 42

# Input/Output
input_image_path: 'data/images/Anh-ve-tinh/Anh-da-pho/HaNoi/b1_1024x1024.tif'
output_image_path: 'outputs/segmented_image.tif'

# Validity indices to calculate
validity_indices:
  dunn_index: false # tràn bộ nhớ Khi kich thước ảnh lớn
  davies_bouldin_index: true # ok
  separation_index: true # ok
  calinski_harabasz_index: true # ok
  silhouette_index: true
  partition_coefficient: true # ok
  classification_entropy: true 
  fuzzy_hypervolume: true # ok
  cs_index: true

# Debug settings
debug:
  print_time: true
  print_image_size: true
  print_steps: true
  print_U: true
  print_V: true
