# General settings
maxiter: 10000
n_clusters: 5
m: 2
epsilon: 0.00001
seed: 42

# Input/Output
input_image_path: 'data/images/Ha Noi.tif'
output_image_path: 'outputs/segmented_image.tif'

# Validity indices to calculate
validity_indices:
  dunn_index: false # Đang bị lỗi tràn bộ nhớ 
  davies_bouldin_index: false
  davies_bouldin_index_sckitlearn: false
  separation_index: false # Đang bị lỗi tràn bộ nhớ 
  partition_coefficient: true
  classification_entropy: false
  fuzzy_hypervolume: false
  cs_index: false

# Debug settings
debug:
  print_time: true
  print_image_size: true
  print_steps: true
  print_U: true
  print_V: true
