# General settings
maxiter: 10000
m: 2
epsilon: 0.00001
seed: 42
data_id: 602 # 53: Iris, 109: Wine, 602: DryBean
num_processes: 16

# Validity indices to calculate
validity_indices:
  dunn_index: false # Đang bị lỗi tràn bộ nhớ 
  davies_bouldin_index: true
  davies_bouldin_index_sckitlearn: true
  separation_index: false # Đang bị lỗi tràn bộ nhớ 
  partition_coefficient: true
  classification_entropy: true
  fuzzy_hypervolume: true
  cs_index: true

# Debug settings
debug:
  print_time: true
  print_image_size: true
  # print_steps: true
  print_U: false
  print_V: false
